import { MediaItem, Genre } from '@/types';

export const GENRES: Genre[] = [
  { id: 28, name: 'Action', slug: 'action' },
  { id: 12, name: 'Adventure', slug: 'adventure' },
  { id: 16, name: 'Animation', slug: 'animation' },
  { id: 35, name: 'Comedy', slug: 'comedy' },
  { id: 80, name: 'Crime', slug: 'crime' },
  { id: 99, name: 'Documentary', slug: 'documentary' },
  { id: 18, name: 'Drama', slug: 'drama' },
  { id: 10751, name: 'Family', slug: 'family' },
  { id: 14, name: 'Fantasy', slug: 'fantasy' },
  { id: 27, name: 'Horror', slug: 'horror' },
  { id: 9648, name: 'Mystery', slug: 'mystery' },
  { id: 10749, name: 'Romance', slug: 'romance' },
  { id: 878, name: 'Sci-Fi', slug: 'sci-fi' },
  { id: 53, name: 'Thriller', slug: 'thriller' },
  { id: 10752, name: 'War', slug: 'war' },
];

export const MOCK_HERO_ITEMS: MediaItem[] = [
  {
    id: 533535,
    tmdb_id: 533535,
    imdb_id: 'tt6263850',
    title: 'Deadpool & Wolverine',
    overview:
      'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
    poster_path: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
    vote_average: 7.7,
    vote_count: 5200,
    release_date: '2024-07-24',
    media_type: 'movie',
    runtime: 128,
    tagline: 'Come together.',
    genres: [
      { id: 28, name: 'Action' },
      { id: 35, name: 'Comedy' },
      { id: 878, name: 'Sci-Fi' },
    ],
    cast: [
      { id: 10859, name: 'Ryan Reynolds', character: 'Wade Wilson / Deadpool', profile_path: 'https://image.tmdb.org/t/p/w185/4SYTH5FRAxwhdkmsqdQ2Vb42qmm.jpg' },
      { id: 6968, name: 'Hugh Jackman', character: 'Logan / Wolverine', profile_path: 'https://image.tmdb.org/t/p/w185/4XujBEq4qU49aLwqA6YkL3j5k0s.jpg' },
      { id: 1373737, name: 'Emma Corrin', character: 'Cassandra Nova', profile_path: 'https://image.tmdb.org/t/p/w185/v56k6G2x0Yt1M4i1d9Yp5V9G1c.jpg' },
      { id: 2283, name: 'Matthew Macfadyen', character: 'Mr. Paradox', profile_path: 'https://image.tmdb.org/t/p/w185/2g3zNn4h4M4Xh4h4h4h4h4h4h.jpg' },
    ],
  },
  {
    id: 693134,
    tmdb_id: 693134,
    imdb_id: 'tt15239678',
    title: 'Dune: Part Two',
    overview:
      'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.',
    poster_path: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520092.jpg',
    vote_average: 8.2,
    vote_count: 6100,
    release_date: '2024-02-27',
    media_type: 'movie',
    runtime: 166,
    tagline: 'Long live the fighters.',
    genres: [
      { id: 878, name: 'Sci-Fi' },
      { id: 12, name: 'Adventure' },
    ],
    cast: [
      { id: 1190668, name: 'Timothée Chalamet', character: 'Paul Atreides', profile_path: 'https://image.tmdb.org/t/p/w185/BE2sdjpgsa2rNTFa66f7upkaOP.jpg' },
      { id: 505710, name: 'Zendaya', character: 'Chani', profile_path: 'https://image.tmdb.org/t/p/w185/r3A7ev7ycA6G3QGgQY7b5r5Bv.jpg' },
      { id: 934, name: 'Rebecca Ferguson', character: 'Lady Jessica', profile_path: 'https://image.tmdb.org/t/p/w185/6NR8N1cM4Y9J1B0x1X5v1b0x1.jpg' },
      { id: 2541, name: 'Javier Bardem', character: 'Stilgar', profile_path: 'https://image.tmdb.org/t/p/w185/6zGk2Z6aW5B7C2F8D1Y9G3Q7Z.jpg' },
    ],
  },
  {
    id: 94605,
    tmdb_id: 94605,
    imdb_id: 'tt11126994',
    title: 'Arcane',
    overview:
      'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.',
    poster_path: 'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn397rWW2vvg.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    vote_average: 8.7,
    vote_count: 4200,
    first_air_date: '2021-11-06',
    media_type: 'tv',
    number_of_seasons: 2,
    number_of_episodes: 18,
    tagline: 'Every legend has a beginning.',
    genres: [
      { id: 16, name: 'Animation' },
      { id: 14, name: 'Fantasy' },
      { id: 878, name: 'Sci-Fi' },
      { id: 28, name: 'Action' },
    ],
    seasons: [
      {
        id: 134187,
        season_number: 1,
        name: 'Season 1',
        episode_count: 9,
        episodes: [
          { id: 1, episode_number: 1, season_number: 1, name: 'Welcome to the Playground', overview: 'Orphaned sisters Vi and Powder bring trouble to Zaun\'s underground streets following a heist in posh Piltover.', still_path: 'https://image.tmdb.org/t/p/w500/abfJJ0G2x83k0XGqX3kYg2P.jpg', runtime: 43 },
          { id: 2, episode_number: 2, season_number: 1, name: 'Some Mysteries Are Better Left Unsolved', overview: 'Idealistic inventor Jayce attempts to harness magic through science — despite his mentor\'s warnings.', still_path: 'https://image.tmdb.org/t/p/w500/5k7mZ5a2y9G6Q5V4P1k3Q8k1.jpg', runtime: 41 },
          { id: 3, episode_number: 3, season_number: 1, name: 'The Base Violence Necessary for Change', overview: 'An epic showdown between old rivals results in a fateful moment for Zaun. Jayce and Viktor risk everything.', still_path: 'https://image.tmdb.org/t/p/w500/8k1xY9k2x6X4b7a1g4G9z1Q3.jpg', runtime: 44 },
          { id: 4, episode_number: 4, season_number: 1, name: 'Happy Progress Day!', overview: 'With Piltover flourishing on their tech, Jayce and Viktor ponder their next move. A familiar face returns.', still_path: 'https://image.tmdb.org/t/p/w500/7a2xY9b4v6X1c3d9g2Z8a1b5.jpg', runtime: 40 },
          { id: 5, episode_number: 5, season_number: 1, name: 'Everybody Wants to Be My Enemy', overview: 'Rogue enforcer Caitlyn tours the Undercity to track down Jinx. Jayce becomes a target in Piltover politics.', still_path: 'https://image.tmdb.org/t/p/w500/3c5b8v7x9z1a4c6e8g2b1d3.jpg', runtime: 40 },
        ],
      },
      {
        id: 134188,
        season_number: 2,
        name: 'Season 2',
        episode_count: 9,
        episodes: [
          { id: 10, episode_number: 1, season_number: 2, name: 'Heavy Is the Crown', overview: 'In the aftermath of the Council attack, Piltover mobilizes for war while Zaun fractures into warring factions.', still_path: 'https://image.tmdb.org/t/p/w500/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg', runtime: 45 },
          { id: 11, episode_number: 2, season_number: 2, name: 'Watch It All Burn', overview: 'Vi struggles with grief and identity. Jinx becomes an accidental icon of rebellion across the Undercity.', still_path: 'https://image.tmdb.org/t/p/w500/abfJJ0G2x83k0XGqX3kYg2P.jpg', runtime: 44 },
        ],
      },
    ],
  },
  {
    id: 100088,
    tmdb_id: 100088,
    imdb_id: 'tt3581920',
    title: 'The Last of Us',
    overview:
      'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey.',
    poster_path: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqmi2979aqbL.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    vote_average: 8.6,
    vote_count: 5100,
    first_air_date: '2023-01-15',
    media_type: 'tv',
    number_of_seasons: 1,
    number_of_episodes: 9,
    tagline: 'When you\'re lost in the darkness, look for the light.',
    genres: [
      { id: 18, name: 'Drama' },
      { id: 878, name: 'Sci-Fi' },
      { id: 12, name: 'Adventure' },
    ],
    seasons: [
      {
        id: 144560,
        season_number: 1,
        name: 'Season 1',
        episode_count: 9,
        episodes: [
          { id: 101, episode_number: 1, season_number: 1, name: 'When You\'re Lost in the Darkness', overview: 'Twenty years after a fungal outbreak ravages the planet, survivors Joel and Tess are tasked with a mission.', still_path: 'https://image.tmdb.org/t/p/w500/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg', runtime: 81 },
          { id: 102, episode_number: 2, season_number: 1, name: 'Infected', overview: 'Joel and Tess journey with Ellie through a desolate and deserted Boston quarantine zone.', still_path: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqmi2979aqbL.jpg', runtime: 53 },
          { id: 103, episode_number: 3, season_number: 1, name: 'Long, Long Time', overview: 'Survivalist Bill prepares for the end of the world until a mysterious stranger arrives.', still_path: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', runtime: 75 },
        ],
      },
    ],
  },
  {
    id: 872585,
    tmdb_id: 872585,
    imdb_id: 'tt15398776',
    title: 'Oppenheimer',
    overview:
      'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II, examining the moral dilemmas and geopolitical consequences of the dawn of the nuclear age.',
    poster_path: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    vote_average: 8.1,
    vote_count: 9400,
    release_date: '2023-07-19',
    media_type: 'movie',
    runtime: 181,
    tagline: 'The world forever changes.',
    genres: [
      { id: 18, name: 'Drama' },
      { id: 36, name: 'History' },
    ],
    cast: [
      { id: 2037, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profile_path: 'https://image.tmdb.org/t/p/w185/360R481845h762295.jpg' },
      { id: 5081, name: 'Emily Blunt', character: 'Katherine Oppenheimer', profile_path: 'https://image.tmdb.org/t/p/w185/360R481845h762295.jpg' },
      { id: 1892, name: 'Matt Damon', character: 'Leslie Groves', profile_path: 'https://image.tmdb.org/t/p/w185/360R481845h762295.jpg' },
      { id: 3223, name: 'Robert Downey Jr.', character: 'Lewis Strauss', profile_path: 'https://image.tmdb.org/t/p/w185/360R481845h762295.jpg' },
    ],
  },
];

export const MOCK_POPULAR_MOVIES: MediaItem[] = [
  ...MOCK_HERO_ITEMS.filter((item) => item.media_type === 'movie'),
  {
    id: 157336,
    tmdb_id: 157336,
    imdb_id: 'tt0816692',
    title: 'Interstellar',
    overview:
      'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    vote_average: 8.4,
    vote_count: 35000,
    release_date: '2014-11-05',
    media_type: 'movie',
    runtime: 169,
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    genres: [
      { id: 12, name: 'Adventure' },
      { id: 18, name: 'Drama' },
      { id: 878, name: 'Sci-Fi' },
    ],
  },
  {
    id: 27205,
    tmdb_id: 27205,
    imdb_id: 'tt1375666',
    title: 'Inception',
    overview:
      'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life as payment for a task considered to be impossible: inception.',
    poster_path: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    vote_average: 8.4,
    vote_count: 36000,
    release_date: '2010-07-15',
    media_type: 'movie',
    runtime: 148,
    tagline: 'Your mind is the scene of the crime.',
    genres: [
      { id: 28, name: 'Action' },
      { id: 878, name: 'Sci-Fi' },
      { id: 12, name: 'Adventure' },
    ],
  },
  {
    id: 155,
    tmdb_id: 155,
    imdb_id: 'tt0468569',
    title: 'The Dark Knight',
    overview:
      'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    poster_path: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    vote_average: 8.5,
    vote_count: 32000,
    release_date: '2008-07-16',
    media_type: 'movie',
    runtime: 152,
    tagline: 'Welcome to a world without rules.',
    genres: [
      { id: 18, name: 'Drama' },
      { id: 28, name: 'Action' },
      { id: 80, name: 'Crime' },
      { id: 53, name: 'Thriller' },
    ],
  },
  {
    id: 550,
    tmdb_id: 550,
    imdb_id: 'tt0137523',
    title: 'Fight Club',
    overview:
      'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.',
    poster_path: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    vote_average: 8.4,
    vote_count: 28000,
    release_date: '1999-10-15',
    media_type: 'movie',
    runtime: 139,
    tagline: 'Mischief. Mayhem. Soap.',
    genres: [
      { id: 18, name: 'Drama' },
      { id: 53, name: 'Thriller' },
    ],
  },
  {
    id: 299536,
    tmdb_id: 299536,
    imdb_id: 'tt4154756',
    title: 'Avengers: Infinity War',
    overview:
      'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos.',
    poster_path: 'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/mDfJG3LC3Dqb67AZ52xYMnVZul.jpg',
    vote_average: 8.3,
    vote_count: 29000,
    release_date: '2018-04-25',
    media_type: 'movie',
    runtime: 149,
    tagline: 'An entire universe. Once and for all.',
    genres: [
      { id: 12, name: 'Adventure' },
      { id: 28, name: 'Action' },
      { id: 878, name: 'Sci-Fi' },
    ],
  },
  {
    id: 496243,
    tmdb_id: 496243,
    imdb_id: 'tt6751668',
    title: 'Parasite',
    overview:
      'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.',
    poster_path: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
    vote_average: 8.5,
    vote_count: 17500,
    release_date: '2019-05-30',
    media_type: 'movie',
    runtime: 132,
    tagline: 'Act like you own the place.',
    genres: [
      { id: 35, name: 'Comedy' },
      { id: 53, name: 'Thriller' },
      { id: 18, name: 'Drama' },
    ],
  },
];

export const MOCK_POPULAR_TV: MediaItem[] = [
  ...MOCK_HERO_ITEMS.filter((item) => item.media_type === 'tv'),
  {
    id: 1399,
    tmdb_id: 1399,
    imdb_id: 'tt0944947',
    title: 'Game of Thrones',
    overview:
      'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north.',
    poster_path: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    vote_average: 8.4,
    vote_count: 23000,
    first_air_date: '2011-04-17',
    media_type: 'tv',
    number_of_seasons: 8,
    number_of_episodes: 73,
    tagline: 'Winter is coming.',
    genres: [
      { id: 10765, name: 'Sci-Fi & Fantasy' },
      { id: 18, name: 'Drama' },
      { id: 10759, name: 'Action & Adventure' },
    ],
    seasons: [
      {
        id: 3624,
        season_number: 1,
        name: 'Season 1',
        episode_count: 10,
        episodes: [
          { id: 63056, episode_number: 1, season_number: 1, name: 'Winter Is Coming', overview: 'Jon Arryn, the Hand of the King, is dead. King Robert Baratheon plans to ask his oldest friend, Eddard Stark, to take his place.', still_path: 'https://image.tmdb.org/t/p/w500/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg', runtime: 62 },
          { id: 63057, episode_number: 2, season_number: 1, name: 'The Kingsroad', overview: 'While Bran recovers from his fall, Ned leaves with his daughters for King\'s Landing. Jon Snow travels north to the Wall.', still_path: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', runtime: 56 },
          { id: 63058, episode_number: 3, season_number: 1, name: 'Lord Snow', overview: 'Ned arrives in King\'s Landing to discover the crown\'s profligacy. At the Wall, Jon impresses Tyrion at the expense of his recruits.', still_path: 'https://image.tmdb.org/t/p/w500/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg', runtime: 58 },
        ],
      },
    ],
  },
  {
    id: 1396,
    tmdb_id: 1396,
    imdb_id: 'tt0903747',
    title: 'Breaking Bad',
    overview:
      'Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live. He chooses to enter the dangerous world of drugs and crime to secure his family\'s future.',
    poster_path: 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    vote_average: 8.9,
    vote_count: 14000,
    first_air_date: '2008-01-20',
    media_type: 'tv',
    number_of_seasons: 5,
    number_of_episodes: 62,
    tagline: 'Change the equation.',
    genres: [
      { id: 18, name: 'Drama' },
      { id: 80, name: 'Crime' },
    ],
    seasons: [
      {
        id: 3572,
        season_number: 1,
        name: 'Season 1',
        episode_count: 7,
        episodes: [
          { id: 62085, episode_number: 1, season_number: 1, name: 'Pilot', overview: 'When an unassuming high school chemistry teacher discovers he has lung cancer, he decides to team up with an ex-student to cook crystal meth.', still_path: 'https://image.tmdb.org/t/p/w500/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg', runtime: 58 },
          { id: 62086, episode_number: 2, season_number: 1, name: 'Cat\'s in the Bag...', overview: 'Walt and Jesse attempt to tie up loose ends following the incident in the desert.', still_path: 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg', runtime: 48 },
        ],
      },
    ],
  },
  {
    id: 66732,
    tmdb_id: 66732,
    imdb_id: 'tt4574334',
    title: 'Stranger Things',
    overview:
      'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    poster_path: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    vote_average: 8.6,
    vote_count: 17000,
    first_air_date: '2016-07-15',
    media_type: 'tv',
    number_of_seasons: 4,
    number_of_episodes: 34,
    tagline: 'Every ending has a beginning.',
    genres: [
      { id: 10765, name: 'Sci-Fi & Fantasy' },
      { id: 18, name: 'Drama' },
      { id: 9648, name: 'Mystery' },
    ],
    seasons: [
      {
        id: 77680,
        season_number: 1,
        name: 'Season 1',
        episode_count: 8,
        episodes: [
          { id: 1198668, episode_number: 1, season_number: 1, name: 'Chapter One: The Vanishing of Will Byers', overview: 'A young boy disappears in Hawkins, Indiana. His friends investigate and meet an unusual girl with telekinetic powers.', still_path: 'https://image.tmdb.org/t/p/w500/56v2KjBlU4XaOv9rVYEQypROD7P.jpg', runtime: 49 },
          { id: 1198669, episode_number: 2, season_number: 1, name: 'Chapter Two: The Weirdo on Maple Street', overview: 'Lucas, Mike, and Dustin try to talk to the girl they found in the woods. Hopper questions Joyce about a phone call.', still_path: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg', runtime: 56 },
        ],
      },
    ],
  },
  {
    id: 105248,
    tmdb_id: 105248,
    imdb_id: 'tt12590266',
    title: 'Cyberpunk: Edgerunners',
    overview:
      'A street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner: a mercenary outlaw also known as a cyberpunk.',
    poster_path: 'https://image.tmdb.org/t/p/w500/7jswOc6jWwENHjhsq2SAjPz917k.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
    vote_average: 8.6,
    vote_count: 2400,
    first_air_date: '2022-09-13',
    media_type: 'tv',
    number_of_seasons: 1,
    number_of_episodes: 10,
    tagline: 'Get in or get out.',
    genres: [
      { id: 16, name: 'Animation' },
      { id: 10759, name: 'Action & Adventure' },
      { id: 10765, name: 'Sci-Fi & Fantasy' },
    ],
    seasons: [
      {
        id: 154817,
        season_number: 1,
        name: 'Season 1',
        episode_count: 10,
        episodes: [
          { id: 2419081, episode_number: 1, season_number: 1, name: 'Let You Down', overview: 'David Martinez struggles to fit in at the prestigious Arasaka Academy while his mother works long hours in the paramedic ward.', still_path: 'https://image.tmdb.org/t/p/w500/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg', runtime: 25 },
          { id: 2419082, episode_number: 2, season_number: 1, name: 'Like a Boy', overview: 'Fitted with a military cyberware Sandevistan, David takes revenge on the student who bullied him and catches Lucy\'s eye.', still_path: 'https://image.tmdb.org/t/p/w500/7jswOc6jWwENHjhsq2SAjPz917k.jpg', runtime: 26 },
        ],
      },
    ],
  },
];

export const ALL_MEDIA_ITEMS: MediaItem[] = [
  ...MOCK_POPULAR_MOVIES,
  ...MOCK_POPULAR_TV,
];
